(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#stars');
if(canvas){const c=canvas.getContext('2d');let W,H,ss=[];
function resize(){W=innerWidth;H=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;c.setTransform(d,0,0,d,0,0);ss=Array.from({length:190},()=>({x:Math.random()*W,y:Math.random()*H,r:.3+Math.random()*1.8,v:.08+Math.random()*.3,a:.2+Math.random()*.8,p:Math.random()*6.28}))}
function draw(){c.clearRect(0,0,W,H);for(const s of ss){s.y+=s.v;s.p+=.02;if(s.y>H)s.y=-2;c.globalAlpha=s.a*(.65+.35*Math.sin(s.p));c.fillStyle='#dce5ff';c.beginPath();c.arc(s.x,s.y,s.r,0,7);c.fill()}requestAnimationFrame(draw)}resize();addEventListener('resize',resize);draw()}
function burst(x,y,n=30){for(let i=0;i<n;i++){let e=document.createElement('span');e.className='conf';e.textContent=['✨','✦','💙','🫶','👑','🎀'][Math.floor(Math.random()*6)];e.style.left=x+'px';e.style.top=y+'px';e.style.setProperty('--x',((Math.random()-.5)*420)+'px');e.style.setProperty('--y',((Math.random()-.5)*420)+'px');document.body.appendChild(e);setTimeout(()=>e.remove(),1500)}}
function toast(t){let e=$('#toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),1800)}
const modal=$('#modal'); $$('.photo, .index-photo').forEach(p=>p.addEventListener('click',e=>{if(!modal)return;e.preventDefault();const img=p.matches('.photo')?p.dataset.img:p.querySelector('img')?.src;if(img){$('#modalImg').src=img;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}}));$('#close')?.addEventListener('click',()=>{modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true')});modal?.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}});
$('#confetti')?.addEventListener('click',e=>{burst(innerWidth/2,innerHeight/2,120);toast('JAJAJA FELICES XV DANNITA 👑✨')});
let candles=15;$('#cake')?.addEventListener('click',e=>{if(candles>0){candles--;$('#candles').textContent=candles?'🕯️ '.repeat(candles):'✨✨✨';burst(e.clientX,e.clientY,6);if(candles===0){$('#wish').classList.add('show');burst(innerWidth/2,innerHeight/2,80)}}});
$$('[data-reveal]').forEach(b=>b.addEventListener('click',()=>{const e=document.getElementById(b.dataset.reveal);e?.classList.add('show');b.textContent='Ya lo viste JAJAJA 💙';b.disabled=true}));
$('#randomCompliment')?.addEventListener('click',()=>{const a=['tu forma de reírte por cualquier tontería','esa mirada que pones cuando estás pensando','lo linda que puedes ser sin darte cuenta','que hasta una conversación random contigo termina siendo un recuerdo','que seas tú, así tal cual, sin tener que aparentar nada'];$('#compliment').textContent='Me gusta de ti '+a[Math.floor(Math.random()*a.length)]+'.';burst(innerWidth/2,innerHeight/2,18)});
const intro=$('#birthdayIntro'),giftWindow=$('#giftWindow'),birthdayCard=$('#birthdayCard');
const openGift=$('#openGift'),enterPage=$('#enterPage'),skipIntro=$('#skipIntro'),closeBirthday=$('#closeBirthday');
function closeIntro(){if(!intro)return;intro.classList.add('closing');setTimeout(()=>{intro.classList.add('hidden');intro.setAttribute('aria-hidden','true')},420)}
openGift?.addEventListener('click',()=>{giftWindow.style.display='none';birthdayCard.classList.add('show');birthdayCard.setAttribute('aria-hidden','false');burst(innerWidth/2,innerHeight/2,45)});
enterPage?.addEventListener('click',closeIntro);skipIntro?.addEventListener('click',closeIntro);closeBirthday?.addEventListener('click',closeIntro);
const cd=document.querySelector('#countdown');if(cd){const target=new Date('2026-10-09T00:00:00-05:00');let shown=false;function tick(){let x=Math.max(0,target-new Date());let d=Math.floor(x/86400000);x%=86400000;let h=Math.floor(x/3600000);x%=3600000;let m=Math.floor(x/60000);let s=Math.floor(x/1000);$('#dd').textContent=d;$('#hh').textContent=h;$('#mm').textContent=m;$('#ss').textContent=s;if(d===0&&h===0&&m===0&&s===0&&!shown){shown=true;const cover=document.createElement('div');cover.className='letter-overlay';cover.innerHTML='<article class="letter-card"><div class="letter-spark">✦ ✧ 💙 ✧ ✦</div><p class="letter-kicker">PARA TI, DANNITA</p><h2>Feliz XV, mi niña</h2><p>Hoy empieza una etapa nueva y quería dejarte algo que pudieras guardar. Ojalá este día te regale recuerdos bonitos, muchas sonrisas y momentos que quieras repetir una y otra vez.</p><p>Gracias por ser tú, con tus ocurrencias, tu forma de reír y esa luz tan tuya. Mereces que te pasen cosas lindas, hoy y siempre.</p><p class="letter-sign">Te quiero muchísimo 🫶</p><button class="btn" id="closeLetter">Volver a la página</button></article>';document.body.appendChild(cover);document.body.classList.add('letter-open');cover.querySelector('#closeLetter').onclick=()=>{cover.remove();document.body.classList.remove('letter-open')}}}tick();setInterval(tick,1000)}
addEventListener('pointerdown',e=>{if(e.target.closest('button,a')){let s=document.createElement('span');s.className='shoot';s.textContent='🕸️';s.style.left=e.clientX+'px';s.style.top=e.clientY+'px';s.style.setProperty('--x',((Math.random()-.5)*180)+'px');s.style.setProperty('--y',(-120-Math.random()*140)+'px');document.body.appendChild(s);setTimeout(()=>s.remove(),850)}});
window.D={burst,toast};
})();